[workspace]
git_tag_name = "{{ package }}/v{{ version }}"
publish = false
semver_check = false

# disable cargo publish for comsic-applet-arch binary.
[[package]]
name = "cosmic-applet-arch"
release = false
# git_release_enable = false

# disable cargo publish for comsic-applet-arch binary.
[[package]]
name = "arch-updates-rs"
publish = true
semver_check = true

[changelog]
# This is based off the default, but adds breaking change description.
# https://release-plz.ieni.dev/docs/config#the-body-field
body = """
\n
## [{{ version | trim_start_matches(pat="v") }}]{%- if release_link -%}({{ release_link }}){% endif %} - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
\n
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}\
{% endif -%}
{% if commit.breaking %}\n     - _{{ commit.breaking_description }}_ {% endif %}
{% endfor -%}
{% endfor %}
\n
"""
