name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux

    steps:
    - name: Install packages
      run: | 
        pacman -Syu rust pacman-contrib pkgconf libxkbcommon git just lld --noconfirm --needed

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build
      run: cargo build --verbose --frozen

    - name: Run tests
      run: | 
        cargo test --verbose --frozen --bins --lib
        cargo test --verbose --frozen --doc
